### ISSUE TITLE
Random Disconnects

### ISSUE THREAD

**Issue by May-I-Help** [MrMeapify/sleepychat#44]
I have an Apple that I use Safari and Firefox to visit and chat on SleepyChat.
When I use Safari I may get disconnected at random times ( at least it seems so to me).
When I use Firefox the connection has been rock solid.
I can visit SleepyChat using different names in each of the browsers and leave them open in chat or on the main page and Safari disconnects many times over a few hours while Firefox remains connected.
I  hope this helps for the future.

Dan

**Comment by ElysianTail** [comment]
Safari is known to not like Sleepychat. Unfortunately, any connection problem is born out of the Socket.io API being used, and thus is nothing I can fix.
