### ISSUE TITLE
Accidentally banned

### ISSUE THREAD

**Issue by Xehanorto** [MrMeapify/sleepychat#45]
I think there was a night two to three months ago where I had accidentally refreshed the chat a few times and I was wondering if it had caused me to be banned by a bot. My name I normally went by was Xehanorto, same as here

**Comment by ElysianTail** [comment]
The connection throttle only locks users out for 10 minutes. It doesn't ban. If you are banned, please contact me at elysiananon@gmail.com for assistance.
