### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by cmd1095** [MrMeapify/sleepychat#48]
So yeah, returning to the site after a long hiatus, aaaand there's one of those captcha things in the sign in screen now, but it's busted, nothing displaying, says

"error invalid domain for site key"

so yeah, can't enter the chatroom, would like to see that remedied if possible.

**Comment by ElysianTail** [comment]
I think you might be using one of the two sleepy-chat domains. Try using
plain Sleepychat.com and see how that works.

**Comment by cmd1095** [comment]
I actually just tried that to attempt my own troubleshooting, since it said something about domains, i just went and googled sleepychat and clicked on it from there, it works now so... yup
